// GENERATED by tools/bookmarks_to_js.py from bookmarks/ahrensburg_ratzeburg.xml
// Do not edit by hand - re-run:
//   python tools/bookmarks_to_js.py bookmarks/ahrensburg_ratzeburg.xml js/bookmarks.js

export const DEFAULT_TOWN = "Ahrensburg";

export const TOWNS = [
  {
    name: "Ahrensburg",
    weCount: 105,
    bounds: [[10.19035, 53.65097], [10.28236, 53.70157]],
    subAreas: [
      { name: "AH: Schäferweg", bounds: [[10.23892, 53.67456], [10.24645, 53.6774]] },
      { name: "AH: Rondeel - Neue Straße", bounds: [[10.23534, 53.67065], [10.246, 53.67466]] },
      { name: "AH: Hermann-Löns-Straße / Gerhart-Hauptmann-Straße", bounds: [[10.22386, 53.6749], [10.23922, 53.68011]] },
      { name: "AH: Gartenholz / Syltring", bounds: [[10.24284, 53.68609], [10.25351, 53.6901]] },
      { name: "AH: Ohlendamm / Waldemar-Bonsels-Weg", bounds: [[10.21499, 53.66306], [10.22565, 53.66708]] },
      { name: "AH: Elsterweg / Elsterstieg", bounds: [[10.23171, 53.65306], [10.2397, 53.65593]] },
      { name: "AH: Bredenbekweg / Am Neuen Teich", bounds: [[10.20503, 53.66637], [10.21818, 53.6711]] },
    ],
  },
  {
    name: "Ratzeburg",
    weCount: 14,
    bounds: [[10.72391, 53.67699], [10.81488, 53.72624]],
    subAreas: [
      { name: "RZ: Bahnhofsallee / Berliner Straße / Matthias-Claudius-Straße", bounds: [[10.74064, 53.69727], [10.74814, 53.70005]] },
      { name: "RZ: Friedrich-Ebert-Straße / Scheffelstraße", bounds: [[10.74659, 53.69749], [10.75248, 53.69967]] },
      { name: "RZ: Wasserstraße / Töpferstraße / Kl. Kreuzstraße / Zum Süßen Grund", bounds: [[10.76954, 53.69899], [10.7765, 53.70156]] },
      { name: "RZ: Seedorfer Straße / Schmilauer Straße", bounds: [[10.78349, 53.68909], [10.79153, 53.69207]] },
    ],
  },
];

export const COMBINED_BOUNDS = [[10.19035, 53.65097], [10.81488, 53.72624]];

