// Searchbar (top-centre of the map): finds a Wirtschaftseinheit by its
// WiE-Nr., its Bezeichnung, or its old Aktenzeichen (Alt-Az), and jumps to
// it. Built from js/we_index.js (generated by tools/we_index.py from
// data/we.fgb - see that script's docstring), since the frontend has no way
// to read the .fgb files and the tiles only expose features in loaded
// tiles, so a global search needs this precomputed instead.
//
// `we` is the app's only queryable layer (see js/layers.js's header), so
// this module - like js/popups.js's BODY_BUILDERS - only ever deals with
// `we`. It is dependency-injected the same way js/overview.js's
// initOverview(map) and js/legend.js's renderLegend(map, ...) are: initSearch
// takes the map plus a small `deps` object (openPopup, searchFitPadding,
// activateArea) rather than reaching into js/app.js's module scope itself.
import { WE_INDEX } from './we_index.js';
import { TOWNS } from './bookmarks.js';
import { stripTownPrefix } from './areas.js';
import { centre } from './overview.js';
import { esc } from './util.js';

// ---- normalisation ---------------------------------------------------
// German street data is the whole reason this isn't a plain substring
// match: "Töpferstraße", "Toepferstrasse" and "Topferstr." all have to find
// the same WiE. Order matters - fold "straße"/"strasse"/"str." to "str"
// BEFORE punctuation is squashed, so "Schmilauer Straße" and
// "Schmilauer Str. 3-7" fold to the same "schmilauer str" prefix; only then
// collapse every run of non-alphanumeric characters (commas, dots, hyphens,
// slashes) to a single space, which is also what turns "34-36" into the two
// tokens "34" and "36" tier-5 matches against Bezeichnung.
function foldStreet(lower) {
  return lower.replace(/straße/g, 'str').replace(/strasse/g, 'str').replace(/str\./g, 'str');
}

function baseNorm(raw) {
  const folded = foldStreet(String(raw).toLowerCase());
  return folded.replace(/[^a-z0-9äöüß]+/g, ' ').replace(/\s+/g, ' ').trim();
}

const UMLAUT_AE = { ä: 'ae', ö: 'oe', ü: 'ue', ß: 'ss' };
/** ä->ae, ö->oe, ü->ue, ß->ss - the "everyone learns this in school" spelling.
 *  Takes an already-baseNorm'd string (a whole Bezeichnung OR a single query
 *  token - both call through this, see tokenize() below, so a query and the
 *  index it's compared against are folded identically). */
function foldAe(base) {
  return base.replace(/[äöüß]/g, (c) => UMLAUT_AE[c]);
}
/** ä->a, ö->o, ü->u, ß->ss - the "typed on a keyboard with no umlauts" spelling. */
function foldBare(base) {
  return base.normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/ß/g, 'ss');
}
function normAe(raw) {
  return foldAe(baseNorm(raw));
}
function normBare(raw) {
  return foldBare(baseNorm(raw));
}

/** true only for a query that is ENTIRELY digits once trimmed - gates the
 *  id/pad/az tiers below so a text query like "Str 5" never accidentally
 *  prefix-matches some WiE-Nr. "5". */
function isNumericQuery(raw) {
  return /^\d+$/.test(String(raw).trim());
}
function stripLeadingZeros(s) {
  return s.replace(/^0+(?=\d)/, '');
}

/** Splits the query into base tokens, then folds EACH token both ways -
 *  the same two spellings every index entry's `bez` is pre-folded into
 *  (bezAe/bezBare below). Folding only the index and not the query was the
 *  bug this comment now guards against: a literal-umlaut query like
 *  "Ostpreußenweg" has to become "ostpreussenweg" (foldAe) / "ostpreussenweg"
 *  (foldBare, ß still -> ss) before it can match either variant. */
function tokenize(raw) {
  return baseNorm(raw)
    .split(' ')
    .filter(Boolean)
    .map((t) => ({ ae: foldAe(t), bare: foldBare(t) }));
}

// bezAe/bezBare/token.ae/token.bare only ever contain [a-z0-9 ], so a plain
// indexOf is enough for both checks - no regex escaping needed.
function wordBoundaryHit(haystack, token) {
  const idx = haystack.indexOf(token);
  return idx !== -1 && (idx === 0 || haystack[idx - 1] === ' ');
}
function tokenHitsBoundary(entry, token) {
  return wordBoundaryHit(entry.bezAe, token.ae) || wordBoundaryHit(entry.bezBare, token.bare);
}
function tokenHitsAnywhere(entry, token) {
  return entry.bezAe.includes(token.ae) || entry.bezBare.includes(token.bare);
}

// ---- index, built once from WE_INDEX ----------------------------------
// Resolves each WiE's containing Untergebiet up front (verified during
// planning: all 119 WiE bbox centres fall inside exactly one
// TOWNS[].subAreas box - see PROGRESS.md), both for the result rows'
// secondary line and for the sidebar activation on selection. A WiE that
// resolves to none is still searchable; it just gets no secondary line and
// no sidebar activation - see the console.warn below and jumpTo()'s own.
function resolveContainingSubArea(bounds) {
  const [cx, cy] = centre(bounds);
  for (const town of TOWNS) {
    for (const sub of town.subAreas || []) {
      const [[w, s], [e, n]] = sub.bounds;
      if (cx >= w && cx <= e && cy >= s && cy <= n) {
        return { townName: town.name, subAreaName: sub.name };
      }
    }
  }
  return null;
}

const NORM_INDEX = WE_INDEX.map((e) => {
  const ug = resolveContainingSubArea(e.bounds);
  if (!ug) {
    console.warn(`search.js: WiE ${e.pad} resolves to no Untergebiet in js/bookmarks.js - js/we_index.js and js/bookmarks.js may be out of sync.`);
  }
  return {
    ...e,
    bezAe: normAe(e.bez),
    bezBare: normBare(e.bez),
    ugTownName: ug ? ug.townName : null,
    ugSubAreaName: ug ? ug.subAreaName : null,
    ugLabel: ug ? stripTownPrefix(ug.subAreaName) : null,
  };
});

// ---- matching -----------------------------------------------------------
// Tiers, best first (lower is better); `we_id` ascending is the tiebreak in
// searchWE() below. A WiE-Nr. match always outranks an Alt-Az match on
// purpose: 33 of the 41 WiE that carry an Alt-Az have one that collides
// with a real WiE-Nr. (e.g. WiE 0813's Alt-Az is "0144", and WiE 0144 also
// exists) - see PROGRESS.md. `tags` records every field that matched, not
// just the winning tier, so a row can carry more than one chip.
function scoreEntry(entry, rawQuery, tokens, numeric) {
  let tier = Infinity;
  const tags = [];

  if (numeric) {
    const q = rawQuery.trim();
    const qNoZero = stripLeadingZeros(q);
    const idStr = String(entry.id);
    if (qNoZero === idStr || q === entry.pad) {
      tags.push({ kind: 'id' });
      tier = Math.min(tier, 1);
    } else if (entry.pad.startsWith(q) || idStr.startsWith(q)) {
      tags.push({ kind: 'id' });
      tier = Math.min(tier, 3);
    }
    for (const az of entry.az) {
      if (q === az || qNoZero === stripLeadingZeros(az)) {
        tags.push({ kind: 'az', value: az });
        tier = Math.min(tier, 2);
      } else if (az.startsWith(q)) {
        tags.push({ kind: 'az', value: az });
        tier = Math.min(tier, 6);
      }
    }
  }

  if (tokens.length) {
    if (tokens.every((t) => tokenHitsBoundary(entry, t))) {
      tags.push({ kind: 'bez' });
      tier = Math.min(tier, 4);
    } else if (tokens.every((t) => tokenHitsAnywhere(entry, t))) {
      tags.push({ kind: 'bez' });
      tier = Math.min(tier, 5);
    }
  }

  return tier === Infinity ? null : { entry, tier, tags };
}

/** Every WiE matching `query`, best tier first, `we_id` ascending within a
 *  tier. Exported for tools/verify.py, which drives the real #search-input
 *  instead of importing this (see js/overview.js's checks for the same
 *  pattern) - kept exported anyway since it is the one pure, DOM-free entry
 *  point a future check could import directly. */
export function searchWE(query) {
  const raw = String(query);
  if (!raw.trim()) return [];
  const numeric = isNumericQuery(raw);
  const tokens = tokenize(raw);
  const out = [];
  for (const entry of NORM_INDEX) {
    const r = scoreEntry(entry, raw, tokens, numeric);
    if (r) out.push(r);
  }
  out.sort((a, b) => a.tier - b.tier || a.entry.id - b.entry.id);
  return out;
}

// ---- dropdown rendering ---------------------------------------------------
const MAX_ROWS = 8;
const TAG_LABEL = { id: 'WiE-Nr.', bez: 'Bezeichnung' };

function tagHtml(tag) {
  const label = tag.kind === 'az' ? `Alt-Az ${esc(tag.value)}` : TAG_LABEL[tag.kind];
  return `<span class="search-tag search-tag--${tag.kind}">${label}</span>`;
}

// One tag per matched field kind, deduped (a query can hit both "id" and
// "bez" tiers on the same row; two "az" hits from a multi-valued Alt-Az
// collapse to one chip listing both values).
function dedupeTags(tags) {
  const byKind = new Map();
  for (const t of tags) {
    if (t.kind === 'az') {
      const prev = byKind.get('az');
      byKind.set('az', prev ? { kind: 'az', value: `${prev.value} / ${t.value}` } : t);
    } else if (!byKind.has(t.kind)) {
      byKind.set(t.kind, t);
    }
  }
  return [...byKind.values()];
}

function rowHtml(result, index) {
  const { entry, tags } = result;
  const tagsHtml = dedupeTags(tags).map(tagHtml).join('');
  const sub = entry.ugLabel ? `<div class="search-result-sub">${esc(entry.ugLabel)}</div>` : '';
  return `
    <li role="option" id="search-opt-${index}" class="search-result" data-index="${index}">
      <div class="search-result-tags">${tagsHtml}</div>
      <div class="search-result-main">
        <span class="search-result-id">${esc(entry.pad)}</span>
        <span class="search-result-bez">${esc(entry.bez)}</span>
      </div>
      ${sub}
    </li>`;
}

// ---- side effects: source-layer feature-state pulse -----------------------
// Adds a `found` feature-state (see js/layers.js's hl-we paint, extended
// alongside `hover` for this feature) toggled on/off three times and then
// left ON, so the searched WiE stays outlined after the animation - not just
// a transient hover. Timer handles are tracked so two fast searches can't
// interleave pulses, and the previous `found` WiE is cleared before the next
// one is set (only one WiE can be "found" at a time).
const PULSE_ON_MS = 300;
const PULSE_OFF_MS = 200;
const PULSE_CYCLES = 3;

function makeFoundState() {
  let timers = [];
  let currentId = null;

  function setFound(map, id, value) {
    map.setFeatureState({ source: 'nl', sourceLayer: 'we', id }, { found: value });
  }
  function cancelTimers() {
    timers.forEach(clearTimeout);
    timers = [];
  }
  return {
    pulse(map, id) {
      cancelTimers();
      if (currentId != null && currentId !== id) setFound(map, currentId, false);
      currentId = id;
      let t = 0;
      for (let i = 0; i < PULSE_CYCLES; i++) {
        timers.push(setTimeout(() => setFound(map, id, true), t));
        t += PULSE_ON_MS;
        timers.push(setTimeout(() => setFound(map, id, false), t));
        t += PULSE_OFF_MS;
      }
      timers.push(setTimeout(() => setFound(map, id, true), t)); // leave on
    },
    clear(map) {
      cancelTimers();
      if (currentId != null) {
        setFound(map, currentId, false);
        currentId = null;
      }
    },
  };
}

// ---- wiring ---------------------------------------------------------------
/** Side-effecting setup, mirroring js/overview.js's initOverview(map) shape.
 *  `deps`:
 *    - openPopup(map, lngLat, hits, activeIndex) -> Popup - js/app.js's own,
 *      exported so a search selection opens the SAME popup code path a map
 *      click does (real tile data, no field duplicated into the index).
 *    - searchFitPadding() -> fitBounds options - js/app.js's own, padded so
 *      the auto-opened popup doesn't cover the WiE it just found.
 *    - activateArea(townName, subAreaRawName) - js/app.js's own, a NO-FLY
 *      sibling of the sidebar's click handling (reveal + is-active only) -
 *      deliberately not the Untergebiet button's own .click(), which would
 *      also fly there and fight the WiE-bounds flight below. */
export function initSearch(map, deps) {
  const input = document.getElementById('search-input');
  const clearBtn = document.getElementById('search-clear');
  const list = document.getElementById('search-results');
  const box = document.getElementById('search');

  const found = makeFoundState();
  let results = [];
  let highlighted = -1;
  let lastPopup = null;

  function closeList() {
    list.hidden = true;
    list.innerHTML = '';
    highlighted = -1;
    input.setAttribute('aria-expanded', 'false');
    input.removeAttribute('aria-activedescendant');
  }

  function renderResults() {
    if (!results.length) {
      list.innerHTML = '<li class="search-empty">Nichts gefunden</li>';
    } else {
      const shown = results.slice(0, MAX_ROWS);
      const rest = results.length - shown.length;
      list.innerHTML = shown.map(rowHtml).join('')
        + (rest > 0 ? `<li class="search-more">${rest} weitere Treffer</li>` : '');
    }
    list.hidden = false;
    input.setAttribute('aria-expanded', 'true');
    highlighted = -1;
    input.removeAttribute('aria-activedescendant');
  }

  function runSearch() {
    const q = input.value;
    clearBtn.hidden = !q;
    if (!q.trim()) {
      closeList();
      return;
    }
    results = searchWE(q);
    renderResults();
  }

  function updateHighlight(rows) {
    rows.forEach((el, i) => el.classList.toggle('is-highlighted', i === highlighted));
    if (highlighted >= 0) {
      input.setAttribute('aria-activedescendant', `search-opt-${highlighted}`);
      rows[highlighted].scrollIntoView({ block: 'nearest' });
    } else {
      input.removeAttribute('aria-activedescendant');
    }
  }

  // Force-shows the `we` layer (reusing the legend's own checkbox handler,
  // js/legend.js, rather than calling setLayoutProperty a second place),
  // resolves+activates the sidebar row (no fly), flies to the WiE's own
  // bounds, pulses it, and opens its popup once the flight settles.
  function jumpTo(entry) {
    const cb = document.getElementById('cb-we');
    if (cb && !cb.checked) {
      cb.checked = true;
      cb.dispatchEvent(new Event('change'));
    }

    if (entry.ugTownName) {
      deps.activateArea(entry.ugTownName, entry.ugSubAreaName);
    }

    map.fitBounds(entry.bounds, { ...deps.searchFitPadding(), maxZoom: 17, duration: 900 });
    found.pulse(map, entry.id);

    map.once('idle', () => {
      const feats = map.querySourceFeatures('nl', {
        sourceLayer: 'we',
        filter: ['==', ['get', 'we_id'], entry.id],
      });
      if (!feats.length) return; // tile for this area failed to load - pulse/fly still happened
      if (lastPopup) lastPopup.remove();
      const hit = { layer: { 'source-layer': 'we' }, properties: feats[0].properties };
      lastPopup = deps.openPopup(map, centre(entry.bounds), [hit], 0);
    });
  }

  function selectResult(result) {
    const entry = result.entry;
    input.value = `${entry.pad} – ${entry.bez}`;
    clearBtn.hidden = false;
    closeList();
    jumpTo(entry);
  }

  input.addEventListener('input', runSearch);

  input.addEventListener('keydown', (e) => {
    if (list.hidden) return;
    const rows = list.querySelectorAll('.search-result');
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      if (!rows.length) return;
      highlighted = Math.min(highlighted + 1, rows.length - 1);
      updateHighlight(rows);
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      if (!rows.length) return;
      highlighted = Math.max(highlighted - 1, 0);
      updateHighlight(rows);
    } else if (e.key === 'Enter') {
      e.preventDefault();
      const idx = highlighted >= 0 ? highlighted : 0;
      if (results[idx]) selectResult(results[idx]);
    } else if (e.key === 'Escape') {
      closeList();
      input.blur();
    }
  });

  list.addEventListener('click', (e) => {
    const li = e.target.closest('.search-result');
    if (!li) return;
    const idx = parseInt(li.dataset.index, 10);
    if (results[idx]) selectResult(results[idx]);
  });

  clearBtn.addEventListener('click', () => {
    input.value = '';
    clearBtn.hidden = true;
    closeList();
    found.clear(map);
    input.focus();
  });

  document.addEventListener('click', (e) => {
    if (!box.contains(e.target)) closeList();
  });
}
