#!/usr/bin/env python3
"""Converts a QGIS spatial-bookmark XML export into js/bookmarks.js.

QGIS bookmark exports record <sr_id>, which is QGIS's INTERNAL srs.db id, not
an EPSG code. For this export the coordinates are EPSG:25832 (ETRS89 / UTM
zone 32N) - confirmed by reprojecting the Ahrensburg bookmark and checking it
encloses the independently-measured Ahrensburg data bounds from the pmtiles
tileset.

Bookmarks are grouped by their <project> element:
  "_Standorte"  -> the two town-level bookmarks (Ahrensburg, Ratzeburg)
  "Ahrensburg" / "Ratzeburg" -> sub-area bookmarks under that town

Usage:
    python tools/bookmarks_to_js.py bookmarks/ahrensburg_ratzeburg.xml js/bookmarks.js

Re-run this after re-exporting bookmarks from QGIS. The XML stays the source
of truth; js/bookmarks.js is generated and should not be hand-edited.
"""
import sys
import xml.etree.ElementTree as ET

# WE (Wirtschaftseinheiten) counts per town, from `ogrinfo -dialect SQLite`
# grouped on `gemeinde` against the source data (see the project plan).
# Hardcoded here rather than derived at runtime: the frontend must not read
# the .fgb files, and this count only changes when the data is re-exported.
WE_COUNTS = {'Ahrensburg': 105, 'Ratzeburg': 14}

SOURCE_EPSG = 25832  # ETRS89 / UTM zone 32N
TARGET_EPSG = 4326


def reproject_bounds(xmin, ymin, xmax, ymax):
    from osgeo import osr
    src = osr.SpatialReference()
    src.ImportFromEPSG(SOURCE_EPSG)
    dst = osr.SpatialReference()
    dst.ImportFromEPSG(TARGET_EPSG)
    src.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
    dst.SetAxisMappingStrategy(osr.OAMS_TRADITIONAL_GIS_ORDER)
    tr = osr.CoordinateTransformation(src, dst)
    lon1, lat1, _ = tr.TransformPoint(xmin, ymin)
    lon2, lat2, _ = tr.TransformPoint(xmax, ymax)
    return [[round(lon1, 5), round(lat1, 5)], [round(lon2, 5), round(lat2, 5)]]


def js_string(s):
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    xml_path, out_path = sys.argv[1], sys.argv[2]

    tree = ET.parse(xml_path)  # ElementTree defaults to UTF-8
    towns = {}       # name -> {bounds}
    subareas = {}     # project -> [ {name, bounds} ]

    for b in tree.getroot():
        name = b.findtext('name')
        project = b.findtext('project')
        xmin, ymin = float(b.findtext('xmin')), float(b.findtext('ymin'))
        xmax, ymax = float(b.findtext('xmax')), float(b.findtext('ymax'))
        bounds = reproject_bounds(xmin, ymin, xmax, ymax)

        if project == '_Standorte':
            towns[name] = bounds
        else:
            subareas.setdefault(project, []).append({'name': name, 'bounds': bounds})

    if set(towns) != set(WE_COUNTS):
        print(f'WARNING: town bookmarks {sorted(towns)} do not match '
              f'expected {sorted(WE_COUNTS)} - update WE_COUNTS in this script', file=sys.stderr)

    # Combined "Beide Standorte" bounds spanning both towns.
    all_lons = [c[0] for b in towns.values() for c in b]
    all_lats = [c[1] for b in towns.values() for c in b]
    combined = [[round(min(all_lons), 5), round(min(all_lats), 5)],
                [round(max(all_lons), 5), round(max(all_lats), 5)]]

    lines = []
    lines.append('// GENERATED by tools/bookmarks_to_js.py from bookmarks/ahrensburg_ratzeburg.xml')
    lines.append('// Do not edit by hand - re-run:')
    lines.append('//   python tools/bookmarks_to_js.py bookmarks/ahrensburg_ratzeburg.xml js/bookmarks.js')
    lines.append('')
    lines.append('export const DEFAULT_TOWN = "Ahrensburg";')
    lines.append('')
    lines.append('export const TOWNS = [')
    for town_name in sorted(towns, key=lambda n: n != 'Ahrensburg'):  # Ahrensburg first
        bounds = towns[town_name]
        we = WE_COUNTS.get(town_name, 0)
        subs = subareas.get(town_name, [])
        lines.append('  {')
        lines.append(f'    name: {js_string(town_name)},')
        lines.append(f'    weCount: {we},')
        lines.append(f'    bounds: {bounds!r},')
        lines.append('    subAreas: [')
        for s in subs:
            lines.append(f'      {{ name: {js_string(s["name"])}, bounds: {s["bounds"]!r} }},')
        lines.append('    ],')
        lines.append('  },')
    lines.append('];')
    lines.append('')
    lines.append(f'export const COMBINED_BOUNDS = {combined!r};')
    lines.append('')

    out = '\n'.join(lines).replace("'", '"') + '\n'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(out)

    n_sub = sum(len(v) for v in subareas.values())
    print(f'Wrote {out_path}: {len(towns)} towns, {n_sub} sub-areas.')


if __name__ == '__main__':
    main()
