#!/usr/bin/env python3
"""Converts data/we.fgb (the pre-tiling WiE export) into js/we_index.js, a
static search index for the searchbar (js/search.js) - the frontend has no
way to read the .fgb files and the tiles only expose features in loaded
tiles, so a global "find any WiE by number/name/Alt-Az" search needs this
precomputed instead.

we.fgb is already reprojected to EPSG:4326 (see CLAUDE.md's export
pipeline) - no coordinate transform needed here, unlike
tools/bookmarks_to_js.py's EPSG:25832 bookmarks.

Usage:
    python tools/we_index.py data/we.fgb js/we_index.js

Re-run this after re-exporting we.fgb. The .fgb stays the source of truth;
js/we_index.js is generated and should not be hand-edited.
"""
import sys

EXPECTED_FEATURE_COUNT = 119  # see CLAUDE.md's layer table - fails loudly if a re-export changes this


def js_string(s):
    return '"' + s.replace(chr(92), chr(92) * 2).replace('"', chr(92) + '"') + '"'


def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)
    fgb_path, out_path = sys.argv[1], sys.argv[2]

    from osgeo import ogr
    ds = ogr.Open(fgb_path)
    if ds is None:
        print(f'ERROR: could not open {fgb_path}', file=sys.stderr)
        sys.exit(1)
    layer = ds.GetLayer(0)

    entries = []
    seen_ids = set()
    errors = []

    for feat in layer:
        we_id = feat.GetField('we_id')
        pad = feat.GetField('we_id_padded')
        bez = feat.GetField('we_bezeichnung')
        az_werte = feat.GetField('az_alt_werte')
        az_padded = feat.GetField('az_alt_padded')
        geom = feat.GetGeometryRef()

        if geom is None:
            errors.append(f'we_id={we_id}: NULL geometry')
            continue
        if not bez:
            errors.append(f'we_id={we_id}: empty we_bezeichnung')
            continue
        if we_id in seen_ids:
            errors.append(f'we_id={we_id}: duplicate')
            continue
        seen_ids.add(we_id)

        # GetEnvelope() -> (minX, maxX, minY, maxY), NOT the (minX, minY,
        # maxX, maxY) order fitBounds()/js/bookmarks.js use - reordered below.
        min_x, max_x, min_y, max_y = geom.GetEnvelope()
        bounds = [[round(min_x, 5), round(min_y, 5)], [round(max_x, 5), round(max_y, 5)]]

        # az_alt_padded mirrors az_alt_werte, zero-padded, " | "-separated
        # when multi-valued (js/fields.js's splitList() convention) - split
        # here so js/search.js gets an array to match against directly, the
        # same way js/popups.js prefers the padded form for display.
        az = []
        if az_padded:
            az = [p.strip() for p in str(az_padded).split('|') if p.strip()]

        entries.append({'id': we_id, 'pad': pad, 'bez': bez, 'az': az, 'bounds': bounds})

    if len(entries) != EXPECTED_FEATURE_COUNT:
        errors.append(f'expected {EXPECTED_FEATURE_COUNT} features, got {len(entries)}')

    if errors:
        print(f'ERROR: {fgb_path} failed validation:', file=sys.stderr)
        for e in errors:
            print(f'  - {e}', file=sys.stderr)
        sys.exit(1)

    entries.sort(key=lambda e: e['id'])

    lines = []
    lines.append('// GENERATED by tools/we_index.py from data/we.fgb')
    lines.append('// Do not edit by hand - re-run:')
    lines.append('//   python tools/we_index.py data/we.fgb js/we_index.js')
    lines.append('//')
    lines.append('// Static search index for js/search.js (the searchbar) - one entry per')
    lines.append('// Wirtschaftseinheit. `bounds` is [[minLon,minLat],[maxLon,maxLat]], the')
    lines.append('// same shape js/bookmarks.js uses for fitBounds(). `az` is [] when the WiE')
    lines.append('// has no Alt-Az. Popup fields are deliberately NOT duplicated here - the')
    lines.append('// popup is built from the live tile feature (see js/app.js/openPopup()),')
    lines.append('// not from this index.')
    lines.append('')
    lines.append('export const WE_INDEX = [')
    for e in entries:
        az_js = '[' + ', '.join(js_string(a) for a in e['az']) + ']'
        lines.append(
            f'  {{ id: {e["id"]}, pad: {js_string(e["pad"])}, bez: {js_string(e["bez"])}, '
            f'az: {az_js}, bounds: {e["bounds"]!r} }},'
        )
    lines.append('];')
    lines.append('')

    out = '\n'.join(lines).replace("'", '"') + '\n'
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write(out)

    n_az = sum(1 for e in entries if e['az'])
    print(f'Wrote {out_path}: {len(entries)} WiE ({n_az} with an Alt-Az).')


if __name__ == '__main__':
    main()
